package org.wojo.QuickAccess.Ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.protocol.packets.interface_.Page;
import com.hypixel.hytale.server.core.asset.type.item.config.ItemStackContainerConfig;
import com.hypixel.hytale.server.core.command.system.CommandManager;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.entity.entities.player.pages.PageManager;
import com.hypixel.hytale.server.core.entity.entities.player.windows.ItemStackContainerWindow;
import com.hypixel.hytale.server.core.entity.entities.player.windows.Window;
import com.hypixel.hytale.server.core.inventory.InventoryComponent;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.inventory.container.ItemStackItemContainer;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;

import org.wojo.QuickAccess.Components.QuickAccessItemComponentFactory;
import org.wojo.QuickAccess.Components.QuickAccessPlayerComponent;
import org.wojo.QuickAccess.Config.QuickAccessConfig;
import org.wojo.QuickAccess.Events.SwapQuickAccessItemEvent;
import org.wojo.QuickAccess.QuickAccessUtils.*;
import org.wojo.QuickAccess.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.util.*;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public abstract class GenericRadialSelectionUi extends InteractiveCustomUIPage<GenericRadialSelectionUi.RadialGuiInteractionData> {

    // ------ UI Interaction Data ------
    public static class RadialGuiInteractionData {
        public String getDebugString() {
            String output =
                    "- Btn Selected: "     + this.buttonSelected +
                    "\n"+" - Bg Img: "     + this.backgroundImage +
                    "\n"+" - Click Type: " + this.clickType;
            return output;
        }

        public String buttonSelected = "N/A";
        public String backgroundImage = "N/A";
        public String clickType = "N/A";
        public static final BuilderCodec<RadialGuiInteractionData> CODEC = BuilderCodec.builder(RadialGuiInteractionData.class, RadialGuiInteractionData::new)
                .append(
                        new KeyedCodec<>("ButtonSelected", Codec.STRING),
                        (obj, val) -> obj.buttonSelected = val,
                        obj -> obj.buttonSelected
                )
                .add()
                .append(
                        new KeyedCodec<>("BackgroundImage", Codec.STRING),
                        (obj, val) -> obj.backgroundImage = val,
                        obj -> obj.backgroundImage
                )
                .add()
                .append(
                        new KeyedCodec<>("ClickType", Codec.STRING),
                        (obj, val) -> obj.clickType = val,
                        obj -> obj.clickType
                )
                .add()
                .build();
    }
    
    // These are updated per each file!
    protected Integer _NUM_QA_BUTTONS = 8;
    protected String _guiFile = QuickAccessConfig.DEFAULT_SELECTION_GUI_FILE;
    protected String _currentBgFile = "";
    protected String _defaultBgFile = "";

    // -2: Default, -1: Equipped Item, 0+: associated Image Icon
    protected int _highlightedSection = -2;
    
    // NOTE: Radial UI's have the following formation
    // - X Selectable items
    // - 1 Equipped Item
    // - Status Button, Settings Button, Help Button
    // See: resources/Common/UI/Custom/Pages/Radials/*

    protected ArrayList<GuiButtonData> _quickAccessButtons = new ArrayList<>();
    protected GuiButtonData _equipedItemButton =  new GuiButtonData(null,"","","","false","","#QuickAccessButtonEquipped","#QuickAccessButtonEquippedImg","","");

    protected GuiButtonData _statusButton = new GuiButtonData(null,"Quick-Swap: Unknown?","","","false","","#QuickAccessButtonStatus","","","");
    protected GuiButtonData _activeStatusButton = new GuiButtonData(null,"To-Active: Disabled","","","false","","#SwapToActiveButtonStatus","","","");
    protected GuiButtonData _inventoryButton = new GuiButtonData(null,"Inventory","","","false","","#OpenInventory","","","");
    protected GuiButtonData _helpButton = new GuiButtonData(null,"Help","","","false","","#QuickAccessButtonHelp","","","");
    protected GuiButtonData _settingsButton = new GuiButtonData(null,"Settings","","","false","","#QuickAccessButtonSettings","","","");


    protected QuickAccessPlayerComponent _playerQaComp = null; // Player Specific Quick Access Settings
    protected Integer _quickAccessItemHotbarPosition = 8;
    protected ItemStack _quickAccessItem = null;               // The Quick Access Item the user is interacting with
    protected ItemStack _targetItem = null;                    // Whats in the location swap will be placed in

    private void setupEquippedButtons() {
        // ------ Setup Equipped Button ------
        if (this._targetItem != null){
            this._equipedItemButton.buttonIcon = this._targetItem.getItemId();
        }
    }
    private void setupSelectionButtons() {
        // ------ Setup Swap Buttons ------

        // Get currently stored items
        ItemStack[] storedItems = QuickAccessUtils.getContainerItems(this._quickAccessItem);
        if (storedItems == null){
            WojosQuickAccessPlugin.LOGGER.atFine().log("[WARN]: Stored items in QuickAccess container is null!");
            QuickAccessUtils.notificationHelper(playerRef.getReference().getStore(), playerRef.getReference(), "WARNING", "You must first add an item to the container inventory to get Radial working.\nUse Right-Click to open container inventory!");
        }

        // For all quick Access buttons
        // -- See if we have a stored Item that could be set to a button
        // -- Update button data with item ID
        for (int qaBtnIt=0; qaBtnIt<this._quickAccessButtons.size(); qaBtnIt++) {
            if (qaBtnIt < storedItems.length) {
                // Enable All buttons that the QuickAccessComp and ItemComp can fit
                this._quickAccessButtons.get(qaBtnIt).isButtonDisabled = "false";
                if (storedItems[qaBtnIt] != null) {
                    this._quickAccessButtons.get(qaBtnIt).buttonIcon = storedItems[qaBtnIt].getItemId();
                }
            }else{
                // We have no more stored items, so break loop.
                return;
            }
        }
    }

    private void setupStaticButtons() {
        if (this._playerQaComp != null && this._playerQaComp.getIsEnabled()) {
            this._statusButton.buttonText = "Quick-Swap: Enabled";
            this._statusButton.buttonStyle = "Color (#00FF00FF)";
        } else {
            this._statusButton.buttonText = "Quick-Swap: Disabled";
            this._statusButton.buttonStyle = "Color (#FF0000FF)";
        }

        if (this._playerQaComp != null && this._playerQaComp.getIsSwapActiveEnabled()) {
            this._activeStatusButton.buttonText = "To-Active: Enabled";
            this._activeStatusButton.buttonStyle = "Color (#00FF00FF)";
        }else{
            this._activeStatusButton.buttonText = "To-Active: Disabled";
            this._activeStatusButton.buttonStyle = "Color (#FF0000FF)";
        }
        WojosQuickAccessPlugin.LOGGER.atFine().log("Active Status Button: "+_activeStatusButton.buttonText);
        
        
        this._helpButton.buttonText = "Help";
        this._settingsButton.buttonText = "Settings";
    }

    protected abstract void constructFileSpecificData();
//    {
//        this._NUM_QA_BUTTONS = 8;
//        this._guiFile = QuickAccessConfig.SELECTION_GUI_FILE_THREE_BY_THREE;
//        this._defaultBgFile = "";
//        this._currentBgFile = "";
//
//        for (int i=0; i<_NUM_QA_BUTTONS; i++) {
//            GuiButtonData btnData = new GuiButtonData(null,"","","","true","", "#QuickAccessButton"+String.valueOf(i),"#QuickAccessButton"+String.valueOf(i)+"Img","HoverImg","PressImg");
//            this._quickAccessButtons.addLast(btnData);
//        }
//    }
    protected void setButtonVisibility(UICommandBuilder uiCommandBuilder) {

        if (this._highlightedSection == -2){
            uiCommandBuilder.set("#HighlightDefault.Visible",true);
        } else if (this._highlightedSection == -1) {
            uiCommandBuilder.set("#HighlightEquipped.Visible",true);
        }else{
            for (int i=0; i<this._NUM_QA_BUTTONS; i++) {
                if (this._highlightedSection == i) {
                    uiCommandBuilder.set("#Highlight"+String.valueOf(i)+".Visible", true);
                }
            }
        }
    }
    
    public GenericRadialSelectionUi(@Nonnull PlayerRef player_ref, Store<EntityStore> store, ItemStack quick_access_item, Integer quick_access_item_hotbar_position) {
        super(player_ref, CustomPageLifetime.CanDismissOrCloseThroughInteraction, RadialGuiInteractionData.CODEC);

        this._quickAccessItem = quick_access_item;
        this._quickAccessItemHotbarPosition = quick_access_item_hotbar_position;

        constructFileSpecificData();
        
        // Save data needed for display (QuickAccessItem Data, QuickAccessPlayerData, Player Event Data)
        // WojosQuickAccessPlugin.LOGGER.atDebug().log("[Debug] Is item held: "+String.valueOf(is_item_held));
        this._playerQaComp = store.getComponent(player_ref.getReference(), QuickAccessPlayerComponent.getComponentType());

        this._targetItem = QuickAccessUtils.getEquippedTargetItemOrNull(player_ref, store);

        // ------ Error Handling ------
        if ( this._quickAccessItem == null ) {
            WojosQuickAccessPlugin.LOGGER.atWarning().log("[Error] No Quick Access Item Held or Equipped!");
        }
        if ( this._playerQaComp == null ) {
            WojosQuickAccessPlugin.LOGGER.atWarning().log("[Error] Player does not have a Quick Access component!");
        }
        if ( this._targetItem == null ) {
            WojosQuickAccessPlugin.LOGGER.atFine().log("[Warn] Player does not have an item in the target location!");
        }
        // ------------------------------- End Data Setup -------------------------------
        // ==============================================================================

        // ------ Setup Icon related buttons ------
        // Equipped 
        this.setupEquippedButtons();
        // Item Select buttons
        this.setupSelectionButtons();

        // ------ Setup non-icon buttons -----
        // Help, Settings, Status
        this.setupStaticButtons();

        // ----------------------------- End Button Configs -----------------------------
        // ==============================================================================

        // Output Used QuickAccess Item information
        WojosQuickAccessPlugin.LOGGER.atFine().log("\n\n------ Item Stack Data ------\n"+this._quickAccessItem.toString());
        WojosQuickAccessPlugin.LOGGER.atFine().log("\n------ Quick Access Item Component ------\n"+ QuickAccessItemComponentFactory.createQuickAccessItemComponent(this._quickAccessItem).getPrintableString());

        // ----------------------------- End Debug Output -----------------------------
        // ============================================================================
    }

    // Take the ButtonData Information and update the associated UI Files
    private void setIconData(UICommandBuilder command_builder, GuiButtonData button_data) {
        if (!Objects.equals(button_data.buttonIcon, "")){
            command_builder.set(button_data.iconHtmlId+".ItemId", button_data.buttonIcon);
        }

        boolean isDiabled = true;
        if ("false".equals(button_data.isButtonDisabled)) {
            isDiabled = false;
        }
        command_builder.set(button_data.buttonHtmlId + ".Disabled", isDiabled);
    }

    private void setItemData(UICommandBuilder command_builder, GuiButtonData button_data){
        if (button_data.buttonMsg != null) {
            command_builder.set(button_data.buttonHtmlId + ".Text", button_data.buttonMsg);
        } else {
            command_builder.set(button_data.buttonHtmlId + ".Text", button_data.buttonText);
        }
        boolean isDiabled = true;
        if ("false".equals(button_data.isButtonDisabled)) {
            isDiabled = false;
        }
        command_builder.set(button_data.buttonHtmlId + ".Disabled", isDiabled);
    }
    
    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        // Setup UI Event Handlers
        for (int qaBtnIt = 0; qaBtnIt < _quickAccessButtons.size(); qaBtnIt++) {
            String htmlID = _quickAccessButtons.get(qaBtnIt).buttonHtmlId;
            String numId = String.valueOf(qaBtnIt);
            String bgImg = "HighlightAreaImgPth"+String.valueOf(qaBtnIt);
            uiEventBuilder.addEventBinding(CustomUIEventBindingType.RightClicking,htmlID, new EventData().append("ButtonSelected", numId).append("BackgroundImage","N/A" ).append("ClickType","RightClick"), true);
            uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating,   htmlID, new EventData().append("ButtonSelected", numId).append("BackgroundImage","N/A" ).append("ClickType",""), true);
            uiEventBuilder.addEventBinding(CustomUIEventBindingType.MouseEntered, htmlID, new EventData().append("ButtonSelected", numId).append("BackgroundImage", bgImg).append("ClickType",""), false);
        }

        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating,   "#QuickAccessButtonEquipped", new EventData().append("ButtonSelected", "equipped").append("BackgroundImage","N/A").append("ClickType",""), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.MouseEntered, "#QuickAccessButtonEquipped", new EventData().append("ButtonSelected", "equipped").append("BackgroundImage", "HighlightAreaImgPthEquipped").append("ClickType",""), false);

        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonHelp",     new EventData().append("ButtonSelected", "help"    ).append("BackgroundImage","N/A").append("ClickType",""), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonStatus",   new EventData().append("ButtonSelected", "status"  ).append("BackgroundImage","N/A").append("ClickType",""), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonSettings", new EventData().append("ButtonSelected", "settings").append("BackgroundImage","N/A").append("ClickType",""), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#SwapToActiveButtonStatus", new EventData().append("ButtonSelected", "swapActive").append("BackgroundImage","N/A").append("ClickType",""), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#OpenInventory", new EventData().append("ButtonSelected", "inventory").append("BackgroundImage","N/A").append("ClickType",""), true);
        // Apply UI File
        uiCommandBuilder.append(this._guiFile);

        setButtonVisibility(uiCommandBuilder);

        WojosQuickAccessPlugin.LOGGER.atFine().log("[INFO] Setting visibility true for: "+this._highlightedSection+"\n");
        //uiCommandBuilder.set("#R1.Background.PatchStyle.TexturePath", "../Radials/Images/Two/QuickAccessRadialMenuDrawing_Two_Default.png");
        //uiCommandBuilder.set("#HighlightDefault.Visible", true);

        // Apply Button Data to the UI Components
        for (int qaBtnIt=0; qaBtnIt < this._quickAccessButtons.size(); qaBtnIt++){
            setIconData(uiCommandBuilder, this._quickAccessButtons.get(qaBtnIt));
        }

        // Apply data to non-icon buttons.
        setIconData(uiCommandBuilder,  this._equipedItemButton);
        setItemData(uiCommandBuilder,  this._settingsButton);
        setItemData(uiCommandBuilder,  this._statusButton);
        setItemData(uiCommandBuilder,  this._activeStatusButton);
        setIconData(uiCommandBuilder,  this._inventoryButton);
        setItemData(uiCommandBuilder,  this._helpButton);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @NonNullDecl RadialGuiInteractionData data) {
        super.handleDataEvent(ref, store, data);

        WojosQuickAccessPlugin.LOGGER.atFine().log("[Info] Handle Event Output Data:\n "+data.getDebugString());
        String buttonPressed = data.buttonSelected;
        String backgroundImg = data.backgroundImage;
        String clickType = data.clickType;
        Boolean isSwapActive_Enabled = this._playerQaComp.getIsSwapActiveEnabled();

        // No Data reveived
        if (buttonPressed.equals("N/A") && backgroundImg.equals("N/A")) {
            WojosQuickAccessPlugin.LOGGER.atFine().log("[INFO] No data found");
            return;
        }

        // Check Bg File Update
        if (!backgroundImg.equals("N/A")) {
            String newBgFile = "";
            if (buttonPressed.equals("equipped")){
                newBgFile = this._equipedItemButton.buttonHighlightImage;
                this._highlightedSection = -1;
            } else {
                this._highlightedSection = Integer.parseInt(buttonPressed);
                newBgFile = this._quickAccessButtons.get(Integer.parseInt(buttonPressed)).buttonHighlightImage;
            }

            if (! newBgFile.equals(this._currentBgFile)) {
                this._currentBgFile = newBgFile;
                WojosQuickAccessPlugin.LOGGER.atFine().log("[INFO] Updating Bg File to "+this._currentBgFile+"\n");
                this.rebuild();
            }
            return;
        }

        switch (buttonPressed) {
            case "settings" -> {
                WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: Settings Pressed");
                PlayerSettingsGui guiPage = new PlayerSettingsGui(playerRef, store);
                Player player = store.getComponent(ref, Player.getComponentType());
                player.getPageManager().openCustomPage(ref, store, guiPage);
            }
            case "status" -> {
                WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: Status Pressed");
                PlayerSettingsGui guiPage = new PlayerSettingsGui(playerRef, store);
                Player player = store.getComponent(ref, Player.getComponentType());
                player.getPageManager().openCustomPage(ref, store, guiPage);
            }
            case "equipped" -> {
                WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: Equipped Pressed");
                this.close();
            }
            case "help" -> {
                WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: Help Pressed");
                String cmd =
                            "echo \"W.I.P. - See one of the following for the current Guides \n" +
                            " - https://github.com/jacobwojoski/hytale.wojos-toolbelt \n" +
                            " - https://wiki.hytalemodding.dev/mod/wojos-quick-access-items-toolbelts-slings-and-more \n" +
                            "Controls: \n"+
                            " * While Holding\n"+
                            "   - Ctrl + Left-Click:   Break block\n"+
                            "   - Ctrl + Right-Click:  Place block\n"+
                            "   - Right-Click:  Open Inventory\n"+
                            "   - Left-Click:   Open Radial UI\n"+
                            "     > Radial + Left-Click:    Swap radial item to target hotbar position\n"+
                            "     > Radial + Right-Click:   Swap to active hotbar position\n"+
                            " * While Placed (Block)\n"+
                            "   - F:            Open Inventory\n"+
                            "   - Ctrl + F:     Equip to Hotbar Position\n"+
                            "   - Left-Click:   Break block dropping inventory\n"+
                            "\"";
                CommandManager.get().handleCommand(playerRef,cmd);
                this.close();
            }
            case "swapActive" -> {
                WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: Swap Active Pressed");
                PlayerSettingsGui guiPage = new PlayerSettingsGui(playerRef, store);
                Player player = store.getComponent(ref, Player.getComponentType());
                player.getPageManager().openCustomPage(ref, store, guiPage);
            }
            case "inventory" -> {
                Player playerComponent = store.getComponent(ref, Player.getComponentType());
                InventoryComponent inventoryComponent = store.getComponent(ref, InventoryComponent.getComponentTypeById(InventoryComponent.HOTBAR_SECTION_ID));
                PageManager pageManager = playerComponent.getPageManager();
                if (this._quickAccessItem != null) {
                    ItemStackContainerConfig config = this._quickAccessItem.getItem().getItemStackContainerConfig();
                    ItemStackItemContainer itemStackItemContainer = ItemStackItemContainer.ensureConfiguredContainer(inventoryComponent.getInventory(), _quickAccessItemHotbarPosition.shortValue(), config);

                    if (itemStackItemContainer != null) {
                        pageManager.setPageWithWindows(ref, store, Page.Bench, true, new Window[]{new ItemStackContainerWindow(itemStackItemContainer)});
                    }
                }
            }
            default -> {
                if ( clickType.equals("RightClick") && isSwapActive_Enabled) {
                    // 
                    short containerPos = Short.parseShort(buttonPressed);
                    short equippedPos = _quickAccessItemHotbarPosition.shortValue();
                    short targetPos = QuickAccessUtils.getActiveHotbarPosition(store,ref);
                    if (targetPos != -1){
                        SwapQuickAccessItemEvent.dispatch(playerRef.getReference(), store, containerPos, equippedPos, targetPos);
                    }
                }else{
                    short containerPos = Short.parseShort(buttonPressed);
                    short equippedPos = _quickAccessItemHotbarPosition.shortValue();
                    short targetPos = (short) _playerQaComp.getTargetPosition();
                    SwapQuickAccessItemEvent.dispatch(playerRef.getReference(), store, containerPos, equippedPos, targetPos);
                }
                this.close();
            }
        }
    }
}
