package org.wojo.QuickAccess.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.QuickAccess.Components.QuickAccessPlayerComponent;
import org.wojo.QuickAccess.Config.QuickAccessConfig;
import org.wojo.QuickAccess.QuickAccessUtils.QuickAccessUtils;
import org.wojo.QuickAccess.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class PlayerSettingsGui extends InteractiveCustomUIPage<PlayerSettingsGui.SettingsUiData> {
    // ------ UI Interaction Data ------
    public static class SettingsUiData {
        public Boolean isEnabled = false;
        public Boolean isActiveSwapEnabled = false;
        public Integer equippedPos = 8;
        public Integer targetPos = 0;
        public String guiFile = QuickAccessConfig.SELECTION_GUI_FILE_GRID_THREE_BY_THREE;
        public String buttonSelected = "";

        public String getDebugString(){
            return String.format("------ SettingsUiData ------\n - IsEnabled: %b\n - equippedPos: %d\n - targetPos: %d\n - guiFile: %s\n - buttonSelected: %s\n - activeSwap: %b",
                this.isEnabled,
                this.equippedPos,
                this.targetPos,
                this.guiFile,
                this.buttonSelected,
                this.isActiveSwapEnabled                 
            );
        }

        public void update(SettingsUiData data){
            this.isEnabled = data.isEnabled;
            this.equippedPos = data.equippedPos;
            this.targetPos = data.targetPos;
            this.guiFile = data.guiFile;
            this.buttonSelected = data.buttonSelected;
            this.isActiveSwapEnabled = data.isActiveSwapEnabled;
        };

        public SettingsUiData(){
        }

        public static final BuilderCodec<SettingsUiData> CODEC = BuilderCodec.builder(SettingsUiData.class, SettingsUiData::new)
            .append(
                new KeyedCodec<>("@IsEnabledCheckbox", Codec.BOOLEAN),
                (obj, val) -> obj.isEnabled = val,
                obj -> obj.isEnabled
            )
            .add()
            .append(
                new KeyedCodec<>("@EquippedNumberField", Codec.INTEGER),
                (obj, val) -> obj.equippedPos = val,
                obj -> obj.equippedPos
            )
            .add()
            .append(
                new KeyedCodec<>("@TargetNumberField", Codec.INTEGER),
                (obj, val) -> obj.targetPos = val,
                obj -> obj.targetPos
            )
            .add()
            .append(
                new KeyedCodec<>("@GuiFileTextField", Codec.STRING),
                (obj, val) -> obj.guiFile = val,
                obj -> obj.guiFile
            )
            .add()
            .append(
                new KeyedCodec<>("ButtonSelected", Codec.STRING),
                (obj, val) -> obj.buttonSelected = val,
                obj -> obj.buttonSelected
            )
            .add()
            .append(
                new KeyedCodec<>("@IsActiveSwapEnabled", Codec.BOOLEAN),
                (obj, val) -> obj.isActiveSwapEnabled = val,
                obj -> obj.isActiveSwapEnabled
            )
            .add()
            .build();
    }

    // ------------ END UI DATA ------------
    SettingsUiData _uiData = new SettingsUiData();

    
    public PlayerSettingsGui(@Nonnull PlayerRef player_ref, Store<EntityStore> store) {
        super(player_ref, CustomPageLifetime.CanDismissOrCloseThroughInteraction, SettingsUiData.CODEC);

        QuickAccessPlayerComponent qaPlayerComp = store.getComponent(player_ref.getReference(), QuickAccessPlayerComponent.getComponentType());
        if (qaPlayerComp != null){
            this._uiData.isEnabled = qaPlayerComp.getIsEnabled();
            this._uiData.equippedPos = qaPlayerComp.getEquippedPosition();
            this._uiData.targetPos = qaPlayerComp.getTargetPosition();
            this._uiData.guiFile = qaPlayerComp.getGuiFile();
            this._uiData.isActiveSwapEnabled = qaPlayerComp.getIsSwapActiveEnabled();
        }
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, 
                      @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiEventBuilder.addEventBinding(
            CustomUIEventBindingType.ValueChanged, "#IsEnabledCheckbox #CheckBox",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","IsEnabledCheckbox")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.ValueChanged, "#IsActiveSwapEnabledCheckbox #CheckBox",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","IsEnabledCheckbox")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.ValueChanged, "#EquippedNumberField",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","EquippedNumberField")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.ValueChanged, "#TargetNumberField",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","TargetNumberField")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.ValueChanged, "#GuiFileTextField",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","GuiFileTextField")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );

        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#RadialTwo",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","RadialTwo")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#RadialThree",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","RadialThree")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#RadialFour",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","RadialFour")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#RadialSix",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","RadialSix")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#RadialEight",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","RadialEight")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );

        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#ResetButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","ResetButton")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#SubmitButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","SubmitButton")
                        .append("@IsActiveSwapEnabled", "#IsActiveSwapEnabledCheckbox #CheckBox.Value"), false
        );

        uiCommandBuilder.append(QuickAccessConfig.SETTINGS_GUI_FILE);

        uiCommandBuilder.set("#IsActiveSwapEnabledCheckbox #CheckBox.Value", _uiData.isActiveSwapEnabled);
        uiCommandBuilder.set("#IsEnabledCheckbox #CheckBox.Value", _uiData.isEnabled);
        uiCommandBuilder.set("#EquippedNumberField.Value", _uiData.equippedPos);
        uiCommandBuilder.set("#TargetNumberField.Value", _uiData.targetPos);
        uiCommandBuilder.set("#GuiFileTextField.Value", _uiData.guiFile);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @NonNullDecl SettingsUiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: Output Settings Data:\n "+data.getDebugString()+"\n\n");
        if (data.buttonSelected.contains("SubmitButton")){
            WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: PlayerSettingsGui - SUBMIT new settings values to player with data\n"+data.getDebugString());

            QuickAccessPlayerComponent newPlayerComp = new QuickAccessPlayerComponent();
            newPlayerComp.setIsEnabled(this._uiData.isEnabled);
            newPlayerComp.setTargetPosition(this._uiData.targetPos);
            newPlayerComp.setEquippedPosition(this._uiData.equippedPos);
            newPlayerComp.setGuiFile(this._uiData.guiFile);
            newPlayerComp.setIsSwapActiveEnabled(this._uiData.isActiveSwapEnabled);

            newPlayerComp = QuickAccessUtils.validateQuickAccessPlayerComponent(newPlayerComp);
            store.replaceComponent(ref, QuickAccessPlayerComponent.getComponentType(), newPlayerComp);
            this.close();
        }else if (data.buttonSelected.contains("ResetButton")) {
            data = new SettingsUiData();
            WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: PlayerSettingsGui - Reset settings values\n");
        }else if (data.buttonSelected.contains("RadialTwo")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_RADIAL_TWO;
            WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: PlayerSettingsGui - Update Gui File to Radial Two\n");
        }else if (data.buttonSelected.contains("RadialThree")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_RADIAL_THREE;
            WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: PlayerSettingsGui - Update Gui File to Radial Three\n");
        }else if (data.buttonSelected.contains("RadialFour")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_RADIAL_FOUR;
            WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: PlayerSettingsGui - Update Gui File to Radial Four\n");
        }else if (data.buttonSelected.contains("RadialSix")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_RADIAL_SIX;
            WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: PlayerSettingsGui - Update Gui File to Radial Six\n");
        }else if (data.buttonSelected.contains("RadialEight")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_RADIAL_EIGHT;
            WojosQuickAccessPlugin.LOGGER.atFine().log("[DEBUG]: PlayerSettingsGui - Update Gui File to Radial Eight\n");
        }

        this._uiData.update(data);
        this.rebuild();
    }
}
