package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.asset.type.item.config.Item;
import com.hypixel.hytale.server.core.command.system.CommandManager;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.inventory.InventoryComponent;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.Components.QuickAccessItemComponentFactory;
import org.wojo.wojosToolbelt.Components.QuickAccessPlayerComponent;
import org.wojo.wojosToolbelt.Config.QuickAccessConfig;
import org.wojo.wojosToolbelt.Events.SwapQuickAccessItemEvent;
import org.wojo.wojosToolbelt.QuickAccessUtils.*;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.util.*;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class ItemSelectionGui extends InteractiveCustomUIPage<ItemSelectionGui.SelectionUiData> {
    // ------ Display data ------
    public static class ButtonData {
        public Message buttonMsg = null;
        public String buttonText = "";

        public String buttonIcon = "";
        public String isButtonDisabled = "false";
        public String buttonStyle = "";

        public ButtonData (Message msg, String icon, String is_disabled, String style){
            this.buttonMsg = msg;
            this.buttonIcon = icon;
            this.isButtonDisabled = is_disabled;
            this.buttonStyle = style;
        }

        public String getDebugString() {
            String output = "-----------\n[DEBUG] ButtonData: \n";
            if (buttonMsg != null){
                output += (" - msg: "+buttonMsg.getRawText())+"\n";
            }else{
                output += " - msg: null\n";
            }

            output += " - text: "+buttonText+"\n";
            output += " - icon: "+buttonIcon+"\n";
            output += " - isDis: "+isButtonDisabled+"\n";
            output += " - style: "+buttonStyle+"\n";
            return output;
        }
    }

    // NOTE: Max size of quick swap UI is 24 items!
    private static final String[]   _QUICK_SWAP_BUTTON_IDS = {
        "#QuickAccessButton0","#QuickAccessButton1","#QuickAccessButton2","#QuickAccessButton3",
        "#QuickAccessButton4","#QuickAccessButton5","#QuickAccessButton6","#QuickAccessButton7",
        "#QuickAccessButton8","#QuickAccessButton9","#QuickAccessButton10","#QuickAccessButton11",
        "#QuickAccessButton12","#QuickAccessButton13","#QuickAccessButton14","#QuickAccessButton15",
        "#QuickAccessButton16","#QuickAccessButton17","#QuickAccessButton18","#QuickAccessButton19",
        "#QuickAccessButton20","#QuickAccessButton21","#QuickAccessButton22","#QuickAccessButton23",
    };

    private String _guiFile = QuickAccessConfig.DEFAULT_SELECTION_GUI_FILE;
    private List<ButtonData> _quickAccessButtons = new ArrayList<>();
    private ButtonData _helpButton = new ButtonData(null,"","","true");
    private ButtonData _settingsButton = new ButtonData(null,"","","true");
    private ButtonData _equipedItemButton =  new ButtonData(null,"","","true");
    private boolean _isQuickAccessItemHeld = false;
    private QuickAccessPlayerComponent _playerQaComp = null;
    private Integer _quickAccessItemHotbarPosition = 8;

    // ------ UI Interaction Data ------
    public static class SelectionUiData {
        public String buttonSelected = "N/A";

        public static final BuilderCodec<SelectionUiData> CODEC = BuilderCodec.builder(SelectionUiData.class, SelectionUiData::new)
                .append(
                        new KeyedCodec<>("ButtonSelected", Codec.STRING),
                        (obj, val) -> obj.buttonSelected = val,
                        obj -> obj.buttonSelected
                )
                .add()
                .build();
    }

    // Get translated names for items the player has stored in the quick access item
    //  - save them to the button data if an item is held
    //  - set button name to `------` if there is nothing stored in quickAccesssItem
    private void loadSelectionButtonData(ItemStack quick_access_item){
        ItemStack[] storedItems = null;
        if (quick_access_item != null){
            storedItems = QuickAccessUtils.getContainerItems(quick_access_item);

            if (storedItems == null){
                WojosQuickAccessPlugin.LOGGER.atInfo().log("[WARN]: Stored items in container is null!");
            }
        }


        // For all UI Buttons were going to set the name to one of the following and get the disabled status of the buttons from the config
        //  - Translated-Item-Name
        //  - Item-ID  (If there is no translation key)
        //  - `------` (If the item slot is empty on the player's container)
        Integer maxQaButtons = QuickAccessConfig.getQuickAccessSize(QuickAccessItemComponentFactory.createQuickAccessItemComponent(quick_access_item));
        WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: QA Button Count: "+maxQaButtons+" ");

        for (int i = 0; i < this._quickAccessButtons.size(); i++){
            ButtonData buttonInfo = this._quickAccessButtons.get(i);

            // Disable all buttons outside max QA item has
            if (i < maxQaButtons) {
                buttonInfo.isButtonDisabled = "false";
            }else{
                buttonInfo.isButtonDisabled = "true";
                buttonInfo.buttonText = "XXX\nXXX\nXXX";
            }

            // Set button info from stored items
            if (storedItems!=null && i<storedItems.length){
                ItemStack storedItem = storedItems[i];
                if (storedItem != null){
                    // Try to get Translation key from item, otherwise use item_id
                    try {
                        String translatedName = Item.getAssetMap().getAsset(storedItems[i].getItemId()).getTranslationKey();
                        Message translated = Message.translation(translatedName);
                        buttonInfo.buttonMsg = translated;
                        WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Saving translated button name for id:"+i);
                    } catch (Exception e) {
                        buttonInfo.buttonText = storedItem.getItemId();
                        WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Saving Item ID Name for id:"+i);
                    }
                }else{
                    // No item Stored in container location
                    buttonInfo.buttonText = "------";
                }
            }
            this._quickAccessButtons.set(i, buttonInfo);
            //WojosQuickAccessPlugin.LOGGER.atInfo().log(_quickAccessButtons.get(i).getDebugString());
        }

        WojosQuickAccessPlugin.LOGGER.atInfo().log("Loaded selection btn info");
//        for (ButtonData button : this._quickAccessButtons){
//            WojosQuickAccessPlugin.LOGGER.atInfo().log("Button: "+button+"\n"+button.getDebugString());
//        }
    }

    private void loadEquippedButtonData(ItemStack target_item) {
        this._equipedItemButton.isButtonDisabled = "false";
        this._equipedItemButton.buttonIcon = "";
        this._equipedItemButton.buttonStyle = "";

        if (target_item != null){
            WojosQuickAccessPlugin.LOGGER.atInfo().log("Equipped item is not null! Its: "+target_item.getItemId());
            try {
                String translatedName = Item.getAssetMap().getAsset(target_item.getItemId()).getTranslationKey();
                this._equipedItemButton.buttonMsg = Message.translation(translatedName);
            } catch (Exception e) {
                this._equipedItemButton.buttonText = target_item.getItemId();
            }
        }else{
            this._equipedItemButton.buttonText = "------";
        }
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Loaded equipped btn info");
    }

    private void loadSettingsAndHelpButtonData() {
        this._settingsButton.buttonText = "Settings";
        this._settingsButton.buttonIcon = "";
        this._settingsButton.isButtonDisabled = "false";
        

        this._helpButton.buttonText = "Help";
        this._helpButton.buttonIcon = "";
        this._helpButton.isButtonDisabled = "false";
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Loaded settings & help btn info");
    }

    public ItemSelectionGui(@Nonnull PlayerRef player_ref, Store<EntityStore> store, Boolean is_item_held) {
        super(player_ref, CustomPageLifetime.CanDismissOrCloseThroughInteraction, SelectionUiData.CODEC);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("[Debug] Is item held: "+String.valueOf(is_item_held));
        this._isQuickAccessItemHeld = is_item_held;
        this._playerQaComp = store.getComponent(player_ref.getReference(), QuickAccessPlayerComponent.getComponentType());
        Player player = store.getComponent(player_ref.getReference(), Player.getComponentType());
        InventoryComponent.Hotbar hotbar = (InventoryComponent.Hotbar) store.getComponent(player_ref.getReference(), InventoryComponent.getComponentTypeById(InventoryComponent.HOTBAR_SECTION_ID));

        for (int i=0; i<_QUICK_SWAP_BUTTON_IDS.length; i++){
            _quickAccessButtons.add(new ButtonData(null,"","","true"));
        }

        ItemStack quickAccessItem = null;
        if (this._isQuickAccessItemHeld){
            quickAccessItem = QuickAccessUtils.getHeldQaItemOrNull(player_ref, store);
            this._quickAccessItemHotbarPosition = (int) hotbar.getActiveSlot();
        }else{
            this._quickAccessItemHotbarPosition = _playerQaComp.getEquippedPosition();
            quickAccessItem = QuickAccessUtils.getEquippedQaItemOrNull(player_ref, store);
        }

        if (this._playerQaComp == null){
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[WARN] Player QA Component is null when opening selection GUI, Using Default of Three By Three Radial");
        } else {
            this._guiFile = _playerQaComp.getGuiFile();
        }

        this.loadSelectionButtonData(quickAccessItem);

        ItemStack targetItem = QuickAccessUtils.getEquippedTargetItemOrNull(player_ref, store);
        this.loadEquippedButtonData(targetItem);

        this.loadSettingsAndHelpButtonData();

        WojosQuickAccessPlugin.LOGGER.atInfo().log("\n\n------ Item Stack Data ------\n"+quickAccessItem.toString());
        WojosQuickAccessPlugin.LOGGER.atInfo().log("\n------ Quick Access Item Component ------\n"+ QuickAccessItemComponentFactory.createQuickAccessItemComponent(quickAccessItem).getPrintableString());
    }

    private void setItemData(UICommandBuilder command_builder, String button_id, ButtonData button_data){
        if (button_id.equals("#QuickAccessButtonEquipped")){
            command_builder.set("#QuickAccessButtonEquippedImg.ItemId", "Quick_Access_Item_Common_Unrestricted");
        }else {
            if (button_data.buttonMsg != null) {
                command_builder.set(button_id + ".Text", button_data.buttonMsg);
            } else {
                command_builder.set(button_id + ".Text", button_data.buttonText);
            }
            boolean isDiabled = true;
            if ("false".equals(button_data.isButtonDisabled)) {
                isDiabled = false;
            }
            command_builder.set(button_id + ".Disabled", isDiabled);
        }
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        switch(this._guiFile){
            case QuickAccessConfig.SELECTION_GUI_FILE_GRID_FIVE_BY_FIVE:
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton23", new EventData().append("ButtonSelected", "23"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton22", new EventData().append("ButtonSelected", "22"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton21", new EventData().append("ButtonSelected", "21"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton20", new EventData().append("ButtonSelected", "20"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton19", new EventData().append("ButtonSelected", "19"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton18", new EventData().append("ButtonSelected", "18"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton17", new EventData().append("ButtonSelected", "17"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton16", new EventData().append("ButtonSelected", "16"), true);

            case QuickAccessConfig.SELECTION_GUI_FILE_GRID_THREE_BY_THREE:
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton7", new EventData().append("ButtonSelected", "7"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton6", new EventData().append("ButtonSelected", "6"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton5", new EventData().append("ButtonSelected", "5"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton4", new EventData().append("ButtonSelected", "4"), true);
            
            default:
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton3", new EventData().append("ButtonSelected", "3"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton2", new EventData().append("ButtonSelected", "2"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton1", new EventData().append("ButtonSelected", "1"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton0", new EventData().append("ButtonSelected", "0"), true);

                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonHelp", new EventData().append("ButtonSelected", "help"), true);
                uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonSettings", new EventData().append("ButtonSelected", "settings"), true);
        }

        if (Objects.equals(this._guiFile, QuickAccessConfig.SELECTION_GUI_FILE_GRID_THREE_BY_THREE) || Objects.equals(this._guiFile, QuickAccessConfig.SELECTION_GUI_FILE_GRID_FIVE_BY_FIVE)){
            uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonEquipped", new EventData().append("ButtonSelected", "equipped"), true);
        }

        uiCommandBuilder.append(this._guiFile);

        switch (this._guiFile){
            case QuickAccessConfig.SELECTION_GUI_FILE_GRID_FIVE_BY_FIVE: // Five By Five
                for (int i=0; i<24; i++){
                    setItemData(uiCommandBuilder, _QUICK_SWAP_BUTTON_IDS[i], this._quickAccessButtons.get(i));
                }
                setItemData(uiCommandBuilder, "#QuickAccessButtonEquipped", this._equipedItemButton);
                break;
            case QuickAccessConfig.SELECTION_GUI_FILE_GRID_THREE_BY_THREE: // Three By Three
                for (int i=0; i<8; i++){
                    setItemData(uiCommandBuilder, _QUICK_SWAP_BUTTON_IDS[i], this._quickAccessButtons.get(i));
                }
                setItemData(uiCommandBuilder, "#QuickAccessButtonEquipped", this._equipedItemButton);
                break;
        }

        setItemData(uiCommandBuilder, "#QuickAccessButtonSettings", this._settingsButton);
        setItemData(uiCommandBuilder, "#QuickAccessButtonHelp", this._helpButton);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @NonNullDecl SelectionUiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Output Data! "+data.buttonSelected);
        String buttonPressed = data.buttonSelected;

        if (buttonPressed.equals("N/A")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("N/A");
            this.close();
        } else if (buttonPressed.equals("settings")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Settings Pressed");
            PlayerSettingsGui guiPage = new PlayerSettingsGui(playerRef, store);
            Player player = store.getComponent(ref, Player.getComponentType());
            player.getPageManager().openCustomPage(ref, store, guiPage);
        } else if (buttonPressed.equals("equipped")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Equipped Pressed");
            this.close();
        } else if (buttonPressed.equals("help")) {
            // TODO: Open help GUI listing commands and guides
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Help Pressed");
            this.close();
        } else{
            this.close();

            // DEBUG: Running command manually for testing
//            String cmd = String.format("wqa item swap --container-pos %s --equipped-pos %d --target-pos %d",
//                buttonPressed,
//                _quickAccessItemHotbarPosition,
//                _playerQaComp.getTargetPosition()
//            );
//            CommandManager.get().handleCommand(this.playerRef, cmd);
//            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Running command: "+cmd);

            short containerPos = Short.parseShort(buttonPressed);
            short equippedPos = _quickAccessItemHotbarPosition.shortValue();
            short targetPos = (short)_playerQaComp.getTargetPosition();
            SwapQuickAccessItemEvent.dispatch(playerRef.getReference(), store, containerPos, equippedPos, targetPos);
        }
    }

}
